name: tmgen
description: A CLI tool for generating bloc/repository/datasource files
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  tmgen: hopegen
